# Generated by Django 4.0.3 on 2022-04-02 16:27

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[bots.models.bot_username_validator]),
        ),
    ]
